# Generated by Django 4.0.1 on 2022-01-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productfeatures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
    ]
