# Generated by Django 4.0.1 on 2022-01-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=255),
        ),
    ]
